communitytools/examples/simpleproject/urls.py
from django.conf.urls.defaults import *
from django.conf import settings

defaultdict = { 'groupName': 'example' }


# newforms admin magic

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Example:
    # (r'^simpleproject/', include('simpleproject.foo.urls')),

    (r'^$', 'django.views.generic.simple.redirect_to', { 'url': '/wiki/show/Start/' }),

    (r'^community/', include('sphene.community.urls'), defaultdict),
    (r'^board/', include('sphene.sphboard.urls'), defaultdict),
    (r'^wiki/', include('sphene.sphwiki.urls'), defaultdict),

    (r'accounts/login/$', 'django.contrib.auth.views.login'),
    (r'accounts/logout/$', 'django.contrib.auth.views.logout' ),

    # Only for development
    (r'^static/sphene/(.*)$', 'django.views.static.serve', {'document_root': settings.ROOT_PATH + '/../../static/sphene' }),

    # Uncomment this for admin:
    (r'^admin/(.*)', admin.site.root),
)

communitytools/sphenecoll/sphene/community/urls.py
from django.conf.urls.defaults import *



urlpatterns = patterns('',
                       (r'captcha/(?P<token_id>\w+).jpg$', 'sphene.community.views.captcha_image'),
                       #(r'accounts/login/$', 'django.contrib.auth.views.login', { 'noGroup': True,
                       #                                                           }),
                       #(r'accounts/register/$', 'django.contrib.auth.views.logout', { 'noGroup': True,
                       #                                                               }),
                       )

urlpatterns += patterns( 'sphene.community.views',
                         (r'accounts/login/$', 'accounts_login'),
                         (r'accounts/logout/$', 'accounts_logout'),
                         (r'accounts/forgot/$', 'accounts_forgot'),
			 
                         (r'profile/(?P<user_id>\d+)/$', 'profile'),
                         (r'profile/edit/$', 'profile_edit_mine'),
                         (r'profile/edit/(?P<user_id>\d+)/$', 'profile_edit'),
                         url(r'profile/(?P<user_id>\d+)/reveal_address/$', 'reveal_emailaddress', name = 'sph_reveal_emailaddress',),

                         url(r'admin/permission/role/list/$', 'admin_permission_role_list', name = 'community_admin_permission_role_list'),
                         url(r'admin/permission/role/edit/(?P<role_id>\d+)/$', 'admin_permission_role_edit'),
                         url(r'admin/permission/role/create/$', 'admin_permission_role_edit', name = 'admin_permission_role_create'),
                         url(r'admin/permission/role/member/(?P<role_id>\d+)/list/$', 'admin_permission_role_member_list'),
                         url(r'admin/permission/role/member/(?P<role_id>\d+)/add/$', 'admin_permission_role_member_add'),
                         url(r'admin/permission/role/member/(?P<role_id>\d+)/addgroup/$', 'admin_permission_role_groupmember_add', ),

                         url(r'admin/permission/rolegroup/list/$', 'admin_permission_rolegroup_list', name = 'community_admin_permission_rolegroup_list'),
                         url(r'admin/permission/rolegroup/edit/(?P<rolegroup_id>\d+)/$', 'admin_permission_rolegroup_edit',),

                         url(r'^accounts/register/$', 'register', name = 'sph_register'),
                         url(r'^accounts/register/(?P<emailHash>[a-zA-Z/\+0-9=]+)/$', 'register_hash', name = 'sph_register_hash'),
                         url(r'^tags/json/autocompletion/$', 'tags_json_autocompletion', name = 'sph_tags_json_autocompletion'),
                         )
urlpatterns += patterns( 'accounts.views',
			(r'accounts/terms/$', 'get_terms', {'terms_template_name': 'sphene/community/register_terms.html'}),
			)

urls.py
from django.conf import settings
from django.conf.urls.defaults import *
from django.contrib import admin

admin.autodiscover()

"""
feeds = {
    'latestpages': LatestPages,
}

sitemaps = {
    'wiki': Wiki,
}
"""

urlpatterns = patterns('',
    url(r'^$', include('Home.urls')),
    url(r'^Publication/', include('Publication.urls')),
    url(r'^Recent_Updates/', include('Recent_Updates.urls')),
    url(r'^Paper_Download/', include('Paper_Download.urls')),
    url(r'^Contact_Us/', include('Contact_Us.urls')),
    url(r'^tinymce/', include('tinymce.urls')),
    url(r'^admin/(.*)', admin.site.root),
    url(r'^%s(?P<path>.*)$' % settings.MEDIA_URL[1:], 
        'django.views.static.serve', {"document_root": settings.MEDIA_ROOT}),
    url(r'^accounts/login/$', 'django.contrib.auth.views.login', {'template_name': 'login.html'}),
    url(r'^accounts/logout/$', include('accounts.urls')),
    url(r'^accounts/register/$', 'sphene.community.views.register', name = 'sph_register'),
    (r'^board/', include('sphene.sphboard.urls')),
    (r'^(?P<urlPrefix>test/(?P<groupName>\w+))/board/', include('sphene.sphboard.urls')),
    (r'^(?P<urlPrefix>test/(?P<groupName>\w+))/wiki/',  include('sphene.sphwiki.urls')),
    (r'^wiki/',  include('sphene.sphwiki.urls'), { 'urlPrefix': 'wiki', 'groupName': 'Sphene' }),
    (r'^static/sphene/(.*)$', 'django.views.static.serve', {'document_root': settings.ROOT_PATH + '/communitytools/static/sphene' }),
    (r'^static/(.*)$', 'django.views.static.serve', {'document_root': settings.ROOT_PATH + '/static' }),
    (r'^site_media/(.*)$', 'django.views.static.serve', {'document_root': '/home/kahless/dev/python/diamanda/media'}), 
    (r'^accounts/register/(?P<emailHash>[a-zA-Z/\+0-9=]+)/$', 'sphene.community.views.register_hash'),
)

communitytools/sphenecoll/sphene/community/models.py
from django.db import models
from django.contrib import admin
from django.contrib.auth.models import User
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes import generic
from sphene.community.sphpermalink import sphpermalink as permalink, get_urlconf
from django.utils.translation import ugettext as _, ugettext_lazy
from django.db import connection
import logging
import re
logger = logging.getLogger('sphene.community.models')
# Create your models here.

class Group(models.Model):
    name = models.CharField(max_length = 250)
    longname = models.CharField(max_length = 250)
    default_theme = models.ForeignKey('Theme', null = True, blank = True)
    parent = models.ForeignKey('Group', null = True, blank = True)
    baseurl = models.CharField(max_length = 250)

    def get_name(self):
        return self.longname or self.name

    def recursiveName(self):
        recname = ''
        if self.parent:
            recname = self.parent.recursiveName() + ' / '
        return recname + self.name

    def get_member(self, user):
        try:
            return GroupMember.objects.get( group = self,
                                            user = user, )
        except GroupMember.DoesNotExist:
            return None

    def __unicode__(self):
        return self.name;



USERLEVEL_CHOICES = (
    (0, ugettext_lazy('Normal User')),
    (5, ugettext_lazy('Administrator')),
    )

class GroupMember(models.Model):
        group = models.ForeignKey( Group )
        user = models.ForeignKey( User, )
        userlevel = models.IntegerField( choices = USERLEVEL_CHOICES )


        changelog = ( ( '2008-04-06 00', 'alter', 'ADD userlevel integer', ),
                      ( '2008-04-06 01', 'update', 'SET userlevel = 0', ),
                      ( '2008-04-06 02', 'alter', 'ALTER userlevel SET NOT NULL', ), )


        def get_userlevel_str(self):
            for value, str in USERLEVEL_CHOICES:
                if value == self.userlevel:
                    return str;



class Theme(models.Model):
        name = models.CharField(max_length = 250)
        path = models.CharField(max_length = 250)

        def __unicode__(self):
                return self.name;


NAVIGATION_URL_TYPES = (
        (0, 'Relative (e.g. /wiki/show/Start)'),
        (1, 'Absolute (e.g. http://sphene.net')
        )

NAVIGATION_TYPES = (
        (0, 'Left Main Navigation'),
        (1, 'Top navigation')
        )

class Navigation(models.Model):
        group = models.ForeignKey(Group)
        label = models.CharField(max_length = 250)
        href  = models.CharField(max_length = 250)
        urltype = models.IntegerField( default = 0, choices = NAVIGATION_URL_TYPES )
        sortorder = models.IntegerField( default = 100 )
        navigationType = models.IntegerField( default = 0, choices = NAVIGATION_TYPES )


        def __unicode__(self):
                return self.label

        class Meta:
                ordering = ['sortorder']
        

class ApplicationChangelog(models.Model):
        app_label = models.CharField(max_length = 250)
        model = models.CharField(max_length = 250)
        version = models.CharField(max_length = 250)
        applied = models.DateTimeField()

        class Meta:
                get_latest_by = 'applied'


from sphene.community.sphsettings import get_sph_setting
#from sphene.community import sphutils

class CommunityUserProfile(models.Model):
    user = models.ForeignKey( User, unique = True)
    displayname = models.CharField(max_length = 250)
    public_emailaddress = models.CharField(max_length = 250)
    
    avatar = models.ImageField( height_field = 'avatar_height',
                                width_field = 'avatar_width',
                                upload_to = get_sph_setting('community_avatar_upload_to'),
                                blank = True, null = True, )
    avatar_height = models.IntegerField(blank = True, null = True, )
    avatar_width = models.IntegerField(blank = True, null = True, )


    changelog = ( ( '2007-08-10 00', 'alter', 'ADD avatar varchar(100)'   ),
                  ( '2007-08-10 01', 'alter', 'ADD avatar_height integer' ),
                  ( '2007-08-10 02', 'alter', 'ADD avatar_width integer'  ),
                  ( '2008-04-10 00', 'alter', 'ADD displayname varchar(250)' ),
                  ( '2008-04-10 01', 'update', "SET displayname = ''" ),
                  ( '2008-04-10 02', 'alter', 'ALTER displayname SET NOT NULL' ),
                )

class CommunityUserProfileField(models.Model):
    """ User profile fields, configurable through the django admin
    interface. """
    name = models.CharField(max_length = 250)
    help_text = models.CharField(max_length = 250, blank = True, help_text = 'An optional help text displayed to the user.' )
    regex = models.CharField(max_length = 250, blank = True, help_text = 'An optional regular expression to validate user input.', )
    renderstring = models.CharField(max_length = 250, blank = True, help_text = 'An optional render string how the value should be displayed in the profile (e.g. &lt;a href="%(value)s"&gt;%(value)s&lt;/a&gt; - default: %(value)s' )
    sortorder = models.IntegerField()

    class Meta:
        ordering = [ 'sortorder' ]


class CommunityUserProfileFieldValue(models.Model):
    user_profile = models.ForeignKey( CommunityUserProfile )
    profile_field = models.ForeignKey( CommunityUserProfileField )

    value = models.CharField( max_length = 250 )

    class Meta:
        unique_together = (("user_profile", "profile_field"),)

class GroupTemplate(models.Model):
    """
    Represents a group specific template which can be used to overload
    any django template from the filesystem.
    """
    group = models.ForeignKey(Group)
    template_name = models.CharField( max_length = 250, db_index = True )
    source = models.TextField()

    def __unicode__(self):
        return self.template_name
    
    class Meta:
        unique_together = (("group", "template_name"),)



class PermissionFlag(models.Model):
    """
    Permission flags are predefined (in the code) flags of user rights.
    Very similar to django's permissions.

    (I decided against using django's permissions for the sake of simplicity..
    i don't like the idea of auto generating permissions which aren't used
    in the application code (but only within the django administration))
    """
    name = models.CharField( max_length = 250, unique = True )


    sph_permission_flags = { 'group_administrator':
                             'Users with this permission flag have all permissions.',

                             'community_manage_roles':
                             'User have permission to create, edit and assign roles.',
                             }


    def __unicode__(self):
        return self.name

class Role(models.Model):
    """
    A role is a user defined collection of so called permission flags.
    """
    name = models.CharField( max_length = 250 )
    group = models.ForeignKey( Group )

    permission_flags = models.ManyToManyField( PermissionFlag, related_name = 'roles' )


    def get_permission_flag_string(self):
        return ", ".join( [flag.name for flag in self.permission_flags.all()] )

    def __unicode__(self):
        return '%s - %s' % (self.group.name, self.name)

    def get_absolute_editurl(self):
        return ('sphene.community.views.admin_permission_role_edit', (), { 'groupName': self.group.name, 'role_id': self.id, } )
    get_absolute_editurl = permalink(get_absolute_editurl, get_urlconf)

    def get_absolute_memberlisturl(self):
        return ('sphene.community.views.admin_permission_role_member_list', (), { 'groupName': self.group.name, 'role_id': self.id, } )
    get_absolute_memberlisturl = permalink(get_absolute_memberlisturl, get_urlconf)

    def get_absolute_memberaddurl(self):
        return ('sphene.community.views.admin_permission_role_member_add', (), { 'groupName': self.group.name, 'role_id': self.id, } )
    get_absolute_memberaddurl = permalink(get_absolute_memberaddurl, get_urlconf)

    def get_absolute_groupmemberaddurl(self):
        return ('sphene.community.views.admin_permission_role_groupmember_add', (), { 'groupName': self.group.name, 'role_id': self.id, } )
    get_absolute_groupmemberaddurl = permalink(get_absolute_groupmemberaddurl, get_urlconf)

    class Meta:
        unique_together = (('name', 'group'),)



class RoleMember(models.Model):
    """
    A role member is the relation between a given role and a 
    1.) user OR 2.) rolegroup - one of those two have to be null !

    This relation can have additional limitations - e.g. for the board
    it might only be active within one given category -
    see RoleMemberLimitation.

    If there are no limitations (has_limitations = False) then the role
    is active for the user globally within the role's group.
    """
    role = models.ForeignKey( Role )
    user = models.ForeignKey( User, null = True )
    rolegroup = models.ForeignKey( 'RoleGroup', null = True )

    has_limitations = models.BooleanField()


    changelog = ( ( '2008-04-15 00', 'alter', 'ALTER user_id DROP NOT NULL', ),
                  ( '2008-04-15 01', 'alter', 'ADD rolegroup_id integer REFERENCES community_rolegroup(id)', ), )

    def get_limitations_string(self):
        if not self.has_limitations:
            return "None"
        limitation = self.rolememberlimitation_set.get()
        return "%s: %s" % (limitation.object_type.model_class()._meta.object_name, unicode(limitation.content_object))



class RoleMemberLimitation(models.Model):
    """
    Limits the membership of a user to a role by only applying to a
    specific object.
    """
    role_member = models.ForeignKey( RoleMember )

    object_type = models.ForeignKey(ContentType)
    object_id = models.PositiveIntegerField(db_index = True)

communitytools/sphenecoll/sphene/community/templates/sphene/community/admin/permission/base.html
{% extends "sphene/community/admin/base.html" %}
{% load i18n %}
{% load sph_extras %}

{% block content %}

<a href="{% sph_url 'community_admin_permission_role_list' %}">{% trans "Role List" %}</a>
{% if role %}
  &gt;&gt; <a href="{{ role.get_absolute_rolememberlist }}">{% trans "Members" %}</a>
{% endif %}<br/><br/>

{% endblock %}

communitytools/sphenecoll/sphene/community/templates/sphene/community/admin/permission/role_edit.html
{% extends "sphene/community/admin/permission/base.html" %}
{% load i18n %}

{% block content %}
{{ block.super }}
<form method="POST" class="sphform" action=".">
  <table class="">
    {{ form }}

    <tr>
      <td colspan="2"><input type="submit" value="{% trans "Store" %}" /></td>
    </tr>
  </table>
</form>

{% endblock %}

communitytools/sphenecoll/sphene/community/templates/sphene/community/admin/permission/role_list.html
{% extends "sphene/community/admin/permission/base.html" %}
{% load i18n %}
{% load sph_extras %}

{% block head %}
  {{ block.super }}
{% endblock %}

{% block content %}

<table>
  <tr>
    <th>{% trans "Options" %}</th>
    <th>{% trans "Name" %}</th>
    <th>{% trans "Flags" %}</th>
    <th>{% trans "Members" %}</th>
  </tr>
  {% for role in roles %}
    <tr>
      <td class="sph_options"><a href="{{ role.get_absolute_editurl }}">{% trans "Edit" %}</a> <a href="{{ role.get_absolute_memberlisturl }}">{% trans "Manage Members" %}</a></td>
      <td class="sph_rolename">{{ role.name }}</td>
      <td>{{ role.get_permission_flag_string }}</td>
      <td>{{ role.rolemember_set.count }}</td>
    </tr>
  {% endfor %}
</table>

<a href="{% sph_url 'admin_permission_role_create' %}">{% trans "Create Role" %}</a>

{% endblock %}

communitytools/sphenecoll/sphene/community/templates/sphene/community/admin/permission/role_member_add.html
{% extends "sphene/community/admin/permission/base.html" %}
{% load i18n %}

{% block content %}
{{ block.super }}
<form method="POST" class="sphform" action=".">
  <table class="">
    {{ form }}

    <tr>
      <td colspan="2"><input type="submit" value="{% trans "Store" %}" /></td>
    </tr>
  </table>
</form>

{% endblock %}

communitytools/sphenecoll/sphene/community/templates/sphene/community/admin/permission/role_member_list.html
{% extends "sphene/community/admin/permission/base.html" %}
{% load i18n %}
{% load sph_extras %}

{% block content %}
  {{ block.super }}

{% blocktrans with role.name as role_name %}Members of the role '{{ role_name }}'.{% endblocktrans %}<br/><br/>

<table>
  <tr>
    <th>&nbsp;</th>
    <th>{% trans "User" %}</th>
    <th>{% trans "Role Group" %}</th>
    <th>{% trans "Limitations" %}</th>
  </tr>
  {% for member in members %}
    <tr>
      <td class="sph_options">[ <a href="?cmd=remove&amp;id={{ member.id }}">{% trans "Remove" %}</a> ]</td>
      <td>{% if member.user %}{% sph_html_user member.user %}{% else %}{% trans "N/A" %}{% endif %}</td>
      <td>{% if member.rolegroup %}{{ member.rolegroup.name }}{% else %}{% trans "N/A" %}{% endif %}</td>
      <td>{{ member.get_limitations_string }}</td>
    </tr>
  {% endfor %}
</table><br/><br/>

<a href="{{ role.get_absolute_memberaddurl }}">{% trans "Add Member" %}</a>
<a href="{{ role.get_absolute_groupmemberaddurl }}">{% trans "Add Rolegroup" %}</a>

{% endblock %}

communitytools/sphenecoll/sphene/community/templates/sphene/community/admin/permission/rolegroup_edit.html
{% extends "sphene/community/admin/permission/base.html" %}

{% load i18n %}
{% load sph_extras %}

{% block content %}

  <p><a href="{% sph_url 'community_admin_permission_rolegroup_list' %}">{% trans "Back to Role Groups" %}</a></p>

  <h1>{% blocktrans with rolegroup.name as rolegroup_name %}Modifying rolegroup '{{ rolegroup_name }}'{% endblocktrans %}</h1>


  <h2>{% trans "Members" %}</h2>

  <table>
    <tr>
      <td></td>
      <th>Username</th>
      <th>User</th>
    </tr>
    {% for member in rolegroup.rolegroupmember_set.all %}
      <tr>
        <td>[ <a href="?cmd=remove&amp;id={{ member.id }}">{% trans "Remove" %}</a> ]</td>
        <td>{{ member.user.username }}</td>
        <td>{{ member.user|sph_html_user }}</td>
      </tr>
    {% endfor %}
  </table>
  
  <h2>{% trans "Add Member" %}</h2>

  <form method="post">
    <label for="username_id">{% trans "Username" %}</label>
    <input type="text" name="username" id="username_id" />
    <input type="submit" value="{% trans "Save" %}" />
  </form>

{% endblock %}

communitytools/sphenecoll/sphene/community/templates/sphene/community/admin/permission/rolegroup_list.html
{% extends "sphene/community/admin/permission/base.html" %}

{% load i18n %}
{% load sph_extras %}

{% block content %}

  <h1>{% trans "Role Groups" %}</h1>

  <table>
    <tr>
      <th>Members</th>
      <th>Name</th>
    </tr>
    {% for rolegroup in rolegroups %}
      <tr>
        <td>{{ rolegroup.rolegroupmember_set.count }}</td>
        <td><a href="{{ rolegroup.get_absolute_editurl }}">{{ rolegroup.name }}</a></td>
      </tr>
    {% endfor %}
  </table>

  <h2>{% trans "Create a new Role Group" %}</h2>
  <form method="post">
    <input type="text" name="name" />
    <input type="submit" value="{% trans "Save" %}" />
  </form>

{% endblock %}